### ISSUE TITLE
Adicionar padrão stretegy à lógica utilizada na classe DoxyparseResults

### ISSUE THREAD

**Issue by MatheusMiranda** [analizo-mes/doxyparse#6]
- [ ] Extrair classe ObjectOriented from DoxyparseResults;
- [ ] Extrair classe Structured from DoxyparseResults;
- [ ] Criar classe classe Results para funcionar como classe abstrata para o strategy;
- [ ] Refatorar classe DoxyparseResults para atuar apenas como manager dos resultados, redirecionando as chamadas;

**Comment by marcelohpf** [comment]
Moved to analizo-mes/analizo repository
